spring.application.name=api-gateway

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=auth-service-users
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/users/**


spring.cloud.gateway.mvc.routes[0].id=appointment-service
spring.cloud.gateway.mvc.routes[0].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/appointments/**


jwt.secret=${JWT_SECRET}
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

